
// $(function() {
	var singing_group_names = [
		"'Round Midnight (MAD)",
		"'Shoptimus Prime (ONT)",
		"3 Men & a Melody (CSD)",
		"4.0 (EVG)",
		"4Ward On! (SLD)",
		"7th Avenue (CAR)",
		"95 North (FWD)",
		"A Mighty Wind (DIX)",
		"Absolut (SNOBS)",
		"Acoustix (SWD) - 1990",
		"After Hours (ILL)",
		"Alexandria Harmonizers (MAD)",
		"Alliance (Quartet) (IAMBS)",
		"Ambassadors of Harmony (CSD)",
		"American Pastime (FWD)",
		"Artistic License (FWD)",
		"Atlanta Vocal Project (DIX)",
		"B.E.A.R.D.S. (CSD)",
		"Backstab (SNOBS)",
		"Blindside (BHA)",
		"Blue Steele (RMD)",
		"Boardwalk (DIX)",
		"Bonus Track (SWD)",
		"Boom! Shakalaka (ILL)",
		"Boomtown (CSD)",
		"Brannigan (FWD)",
		"Brothers In Arms (MAD)",
		"Brothers in Harmony (MAD)",
		"BSQ (MAD)",
		"Carolina Vocal Express (NSC)",
		"Central Standard (CSD)",
		"CHORD SMASH! (LOL)",
		"Circle City Sound (CAR)",
		"Clutch (SWD)",
		"ColdSnap (SLD)",
		"Common Core (JAD)",
		"Cottontown Chorus (BABS)",
		"Crossroads (CSD) – 2009",
		"Cutting Edge (CAR)",
		"Da Capo (MAD)",
		"Dad Wagon (DIX)",
		"Downeasters (NED)",
		"Downtown Crossing (NED)",
		"Duke City Sound (RMD)",
		"Eclectones (FWD)",
		"Entertainmen (SNOBS)",
		"Entourage (SWD)",
		"Euphoria (MAD)",
		"Fast Track (NED)",
		"Finest Hour (BABS)",
		"Flightline (FWD)",
		"Flipside (EVG)",
		"Forefront (CAR)",
		"Four Voices (DIX) – 2002)",
		"Frank the Dog (MAD)",
		"FRED (DIX) – 1999",
		"Frontier (PIO)",
		"Fuego (SUN)",
		"Fusion (SLD)",
		"G-Fours (PIO)",
		"Game of Tones (SLD)",
		"Gas House Gang (CSD) – 1997",
		"Gimme Four (MAD)",
		"Glen Arven Ave (DIX)",
		"Gotcha! (FWD) – 2004",
		"GQ (LOL)",
		"Grand Design (LOL)",
		"Great Lakes Chorus (PIO)",
		"Great Northern Union (LOL)",
		"Hallmark of Harmony (BABS)",
		"Harbourtown Sound (ONT)",
		"Harmonium (CSD)",
		"Heralds of Harmony (SUN)",
		"HHHHHHHHHHHHHH (EVG)",
		"Highland Drive (RMD)",
		"Hot Air Buffoons (JAD)",
		"Houston Tidelanders (SWD)",
		"IFK Barbershop (SNOBS)",
		"Instant Classic (CAR) - 2015",
		"Instant Message (DIX)",
		"Jam Session (JAD)",
		"Joker's Wild (JAD) – 1998",
		"Kordal Kombat (LOL)",
		"KVU (CAR)",
		"Last Chance (NED)",
		"Last Men Standing (MAD)",
		"Late Shift (CAR)",
		"Lemon Squeezy (SNOBS)",
		"Let's Hear it Four! (JAD)",
		"Let's Sing (NSC)",
		"Livewire (CSD)",
		"Lockness (SNOBS)",
		"Lockout (BHA)",
		"Looking Sharp (SLD)",
		"Loop 10 (DIX)",
		"Lunch Break (DIX)",
		"Madison Park (EVG)",
		"Maelstrom (DABS)",
		"Main Street (SUN)",
		"Majestyx (PIO)",
		"Makeshift (SWD)",
		"Marcsmen (SWD)",
		"Masterpiece (FWD) – 2013",
		"Masters of Harmony (FWD)",
		"Max Q (SWD) – 2007",
		"Mayhem (MAD)",
		"MC4 (DIX)",
		"McPhly (FWD)",
		"Men2Be (DABS)",
		"Men In Black (NED)",
		"Men of Independence (JAD)",
		"Michigan Jake (CAR) – 2001",
		"Midnight Croon (LOL)",
		"Midwest Standard (JAD)",
		"Midwest Vocal Express (LOL)",
		"Momentous (RMD)",
		"Momma's Boys (EVG)",
		"MountainTown Singers (PIO)",
		"Music City Chorus (DIX)",
		"Musical Island Boys (BHNZ) – 2014",
		"New Tradition (ILL)",
		"No Strings Attached (NSC)",
		"North of The Border (FWD)",
		"Northwest Sound (EVG)",
		"Northwest Vocal Project (EVG)",
		"OC Times (FWD) – 2008",
		"Ocean's 4 (SNOBS)",
		"Ohana Means Family (DIX)",
		"Old School (MAD) – 2011",
		"On Point (SUN)",
		"Overture (DIX)",
		"Palmetto Vocal Project (NSC)",
		"Park Street (BABS)",
		"Pathfinder Chorus (CSD)",
		"PLATINUM (SUN) – 2000",
		"Polaris (SWD)",
		"Portobello Road (BABS)",
		"Power Play (PIO) – 2003",
		"Prelude (JAD)",
		"Premium Blend (CSD)",
		"Q-Tones (SNOBS)",
		"Quorum (JAD)",
		"Realtime (EVG) – 2005",
		"Reckless (BABS)",
		"RedZone (DIX)",
		"Ringmasters (SNOBS) – 2012",
		"Riverside Ringers (NSC)",
		"Rooftop Records (SUN)",
		"Route 1 (MAD)",
		"Saltaires (RMD)",
		"Salty Dog (CSD)",
		"Saturday Evening Post (SWD)",
		"Secondary Dominants! (SWD)",
		"Senate-Aires (EVG)",
		"Shockapella (CSD)",
		"Shockapella (CSD)",
		"Signature (SUN)",
		"Skyline (BHA)",
		"SNAFU (EVG)",
		"Sold Out (EVG)",
		"Sound of Illinois (ILL)",
		"Sound of the Rockies (RMD)",
		"Southern Gateway Chorus (JAD)",
		"Spirit of Phoenix (FWD)",
		"Stockholm Syndrome (SNOBS)",
		"Storm Front (RMD) – 2010",
		"Students of the Game (MAD)",
		"Supertonic (ONT)",
		"SwitchBack (CSD)",
		"Tagline (BABS)",
		"Take Four (BinG!)",
		"Test Drive (ONT)",
		"The 865 (DIX)",
		"The Academy (SUN)",
		"The Alliance (JAD)",
		"The Alliance Chorus (JAD)",
		"The B-Flads (BHNZ)",
		"The Boulevard (CSD)",
		"The Collective (CAR)",
		"The Con Men (JAD)",
		"The Core (JAD)",
		"The Crew (JAD)",
		"The Crush (FWD)",
		"The Emerald Guard (BABS)",
		"The Essentials (SWD)",
		"The Establishment (BHA)",
		"The Grand Angus (BHA)",
		"The Hanfris Quartet (SABS)",
		"The Institute (SUN)",
		"The InsurGents (DIX)",
		"The Locksmiths (BABS)",
		"The Major Four-Teens (SLD)",
		"The Marcsmen (SWD)",
		"The Mellow Diners (BHA)",
		"The Mission (BHNZ)",
		"The Newfangled Four (FWD)",
		"The Pine (RMD)",
		"The Reen Brothers (JAD)",
		"The Reunion (NED)",
		"The Rooftops (CAR)",
		"The Society (SUN)",
		"The Summit (RMD)",
		"The Sunny Boys (SUN)",
		"The Underground (LOL)",
		"Those Meddling Kids (ONT)",
		"Throwback (SUN)",
		"THX (SUN)",
		"Timepiece (NED)",
		"TLA (BHA)",
		"TNS (DIX)",
		"Toronto Northern Lights (ONT)",
		"Trailblazers (BABS)",
		"Trocadero (SNOBS)",
		"U-BET! (EVG)",
		"Union Station (ILL)",
		"Up All Night (MAD)",
		"Upper Deck (PIO)",
		"Upstate Harmonizers (SLD)",
		"Valiant (FWD)",
		"Vantage Point (SUN)",
		"Vocal Edition (FWD)",
		"Vocal FX (BHNZ)",
		"Vocal Majority (SWD)",
		"Vocal Revolution (NED)",
		"Vocal Spectrum (CSD) – 2006",
		"Vocality (LOL)",
		"Voices in Harmony (FWD)",
		"Voices of California (FWD)",
		"Voices of Gotham (MAD)",
		"Westminster Chorus (FWD)",
		"Without A Doubt! (CAR)",
		"Yonge Guns (ONT)",
		"Zero Hour (NSC)",
		"zero8 (SNOBS)",
	];

	// $( ".singing_group_autocomplete" ).autocomplete({
	// 	source: singing_group_names
	// });

// });
